/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.68 (1.7.4)
 * Generated at: 2019-05-04 03:07:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Templates/header.jsp", Long.valueOf(1556938447718L));
    _jspx_dependants.put("/Templates/footer.jsp", Long.valueOf(1556938941723L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=windows-1252");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("         <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1252\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <script type=\"text/javascript\"  src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\"  src=\"js/bootstrap.js\"></script>\r\n");
      out.write("        <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("        <title>Aislamientos</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>    \r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("<div id=\"login\">\r\n");
      out.write("   ");
      out.write("<nav class=\"navbar navbar-inverse \" style='background-color: rgb(0,60,130)'>\n");
      out.write("    <div class=\"container-fluid\" >\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("            <img src=\"imgs/logo.png\" width=\"120\" height=\"40\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("            <h3 style=\"color: white\">&nbsp;&nbsp;&nbsp;Professional Inventory Control System </h3>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("   \r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4\"></div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h3>Login</h3>\r\n");
      out.write("              <form action=\"\" method=\"post\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label class=\"control-label\" for=\"name\">Usuario :</label>\r\n");
      out.write("                  <input class=\"form-control\" id=\"username\" name=\"username\" placeholder=\"usuario\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label class=\"control-label\" for=\"password\">Password :</label>\r\n");
      out.write("                  <input class=\"form-control\" id=\"password\" name=\"password\" placeholder=\"**********\" type=\"password\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-default\" name=\"submit\" >Login</button>\r\n");
      out.write("              </form>  ");
 String errorDescription = (String) request.getAttribute("shiroLoginFailure");  if (errorDescription!=null) {   
      out.write("\r\n");
      out.write("                    <p class=\"text-danger\">Error de acceso</p>  ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"col-md-4\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("                   <!-- ");
      out.write("<footer>\n");
      out.write("    <div class=\"container-fluid\" style=\"text-align: center\">\n");
      out.write("        Champion Air Cargo - Desarrollado por David Herrera - Ingeniero I+D<br>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write(" -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
